# Generated by Django 3.2.5 on 2021-07-13 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('sub_Categories', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('pin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pin_id2', models.CharField(default='', max_length=100)),
                ('pin_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('price_not', models.IntegerField(default=999)),
                ('desc', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
                ('image1', models.ImageField(default='', null=True, upload_to='pin/images')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='pin/images')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='pin/images')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='pin/images')),
                ('category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='seller.category', verbose_name='Category')),
                ('shop', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('photo', models.ImageField(default='default.png', upload_to='user_photos')),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('seller_Name', models.CharField(max_length=500, null=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('seller_Address', models.TextField()),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('landmark', models.CharField(blank=True, max_length=500, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('ihearte', 'ihearte'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=50, null=True)),
                ('account_Holder_Name', models.CharField(max_length=50, null=True)),
                ('account_Number', models.CharField(max_length=20, null=True)),
                ('ifsc_Code', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='seller_slider_img')),
                ('url', models.CharField(default='#', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('product', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.pin')),
            ],
        ),
        migrations.CreateModel(
            name='PinSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.pin')),
            ],
        ),
        migrations.CreateModel(
            name='PinSetOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=50)),
                ('pins', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='', max_length=15)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinSet',
            fields=[
                ('pinSet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pinSet_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('color', models.TextField(verbose_name='Enter Color Separated by Comma')),
                ('number_of_pins', models.IntegerField(default=0, null=True)),
                ('pub_date', models.DateField(auto_now=True)),
                ('image1', models.ImageField(default='', null=True, upload_to='pinSet/images')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='pinSet/images')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='pinSet/images')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='pinSet/images')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='seller.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='PinReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=50)),
                ('seller', models.CharField(default='iheart@admin', max_length=100)),
                ('pins', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='', max_length=15)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('pin', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.pin', verbose_name='Pin Id')),
            ],
        ),
    ]
