# Generated by Django 3.2.5 on 2021-07-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_category_sub_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='product',
            new_name='pin',
        ),
    ]
