# Generated by Django 3.2.5 on 2021-07-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_alter_userdetail_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='pin_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_size',
            new_name='pin_size',
        ),
    ]
